# Generated by Django 6.1.2 on 2026-10-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_assessment_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0), ('weight__lte', 100)), name='assessment_weight_0_100'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='assessment_max_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', models.F('max_score'))), _connector='OR'), name='assessment_score_valid'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('area', 'personal'), _negated=True), models.Q(('kind', 'general'), ('subject__isnull', True), ('project__isnull', True)), _connector='OR'), name='task_personal_general_unlinked'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'exam'), _negated=True), ('due_date__isnull', False), _connector='OR'), name='task_exam_requires_due_date'),
        ),
    ]
